### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by monocode-ir** [cafebazaar/bundle-signer#2] opened 2021-06-20 13:28 UTC
hello
after run below command to make bin: 
`java -jar bundlesigner-0.1.0.jar genbin  -v --bundle app-release.aab --bin C:/reactnative/  --v2-signing-enabled true --ks mycert.jsk --ks-key-alias cafebazaar`

the following error occurs:
`Exception in thread "main" java.nio.file.FileSystemException: tmp_signer\app-release.apks: The process cannot access the file because it is being used by another process.

        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
        at java.nio.file.Files.deleteIfExists(Unknown Source)
        at shadow.bundletool.com.android.utils.PathUtils.deleteRecursivelyIfExists(PathUtils.java:58)
        at shadow.bundletool.com.android.utils.PathUtils.deleteRecursivelyIfExists(PathUtils.java:53)
        at shadow.bundletool.com.android.utils.FileUtils.deleteRecursivelyIfExists(FileUtils.java:238)
        at ir.cafebazaar.bundlesigner.BundleSignerTool.main(BundleSignerTool.java:138)
`

and `tmp_signer` folder with (app-release.apks-default.keystore) created

what can i do?

**Comment by mahboobehad** [comment] 2021-06-22 11:47
Hello!
Thanks for the report. There's an issue with our tool on Windows and we're working on it. Please try using the latest version on a UNIX-based OS.

**Comment by mahboobehad** [comment] 2021-06-23 06:54
The issue is fixed now. Please download [the latest version](https://github.com/cafebazaar/bundle-signer/releases/tag/v0.1.2) and try again on Windows.

**Closed** 2021-06-23 07:15 UTC
